<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__s</name>
   <tag></tag>
   <elementGuidId>0ee4fb24-3853-4670-92b7-cbf7b0146280</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.headerdiv > div.main_search > #search_widget > div.searchtoggle > form > input[name=&quot;s&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='s'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Rechercher&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c761ee9-bfb8-47f4-b6c9-b169ef25d2ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1673dbad-cb4f-4d24-b61e-ea2b57aab633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>6ace3313-a91b-4aa4-ab76-c5593c13bec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rechercher...</value>
      <webElementGuid>7219184b-8a77-4fb2-aba5-4c00860daf5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Rechercher</value>
      <webElementGuid>40376b09-33f3-4539-a224-958d657913a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header-top&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;headerdiv&quot;]/div[@class=&quot;main_search&quot;]/div[@id=&quot;search_widget&quot;]/div[@class=&quot;searchtoggle&quot;]/form[1]/input[2]</value>
      <webElementGuid>ab68e296-b6e4-4942-8224-0630b6841cfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='s'])[3]</value>
      <webElementGuid>b9f33d40-6088-4de8-a397-f71eff331b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='search_widget']/div/form/input[2])[3]</value>
      <webElementGuid>4a44ed88-e747-4ac5-95cc-550245255c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/form/input[2]</value>
      <webElementGuid>b1a5cb2f-c7a7-4eff-9bdc-652d11c651ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 's' and @placeholder = 'Rechercher...']</value>
      <webElementGuid>80382ae4-fc1a-48a4-a9d4-9630b5a24c12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
