<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__s</name>
   <tag></tag>
   <elementGuidId>0ee4fb24-3853-4670-92b7-cbf7b0146280</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.headerdiv > div.main_search > #search_widget > div.searchtoggle > form > input[name=&quot;s&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='s'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Rechercher&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>484e7185-4150-4c3e-b73e-29945998c1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>82247263-d8e9-4fd8-8d5d-587e9bf3f8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>5d9c2cf1-c66a-4bd5-90b3-1f28e4b4475e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rechercher...</value>
      <webElementGuid>b702baaf-6ddd-4984-bd77-2ee873310dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Rechercher</value>
      <webElementGuid>a4a4410c-9601-45e8-9915-0485dddc6d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header-top&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;headerdiv&quot;]/div[@class=&quot;main_search&quot;]/div[@id=&quot;search_widget&quot;]/div[@class=&quot;searchtoggle&quot;]/form[1]/input[2]</value>
      <webElementGuid>cf8b50c3-9add-4ba5-ab86-d174856c0e7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='s'])[3]</value>
      <webElementGuid>2d0317a1-07d0-450c-ab71-54f172ada7a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='search_widget']/div/form/input[2])[3]</value>
      <webElementGuid>8416c438-70f5-4ce5-8a24-92b236977105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/form/input[2]</value>
      <webElementGuid>943bdddc-a30b-4963-b616-99f76c05e8ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 's' and @placeholder = 'Rechercher...']</value>
      <webElementGuid>2b1f4270-bae4-428e-aa4a-26bc25d676f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
