<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Connexion</name>
   <tag></tag>
   <elementGuidId>a08b0ed3-0a20-4a62-892f-5de74a0c854a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submit-login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submit-login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Connexion&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>55a0a04f-912f-434b-97d3-eaca055d1648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit-login</value>
      <webElementGuid>c50206a6-fcc9-430c-8687-1a4003775879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>175ec744-8507-4694-af3d-8a2f59c167b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link-action</name>
      <type>Main</type>
      <value>sign-in</value>
      <webElementGuid>b1d89451-25de-4836-a44c-ae41e666fa9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f12db1c1-1155-4cd2-b659-6c3c01fa59c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Connexion
          </value>
      <webElementGuid>99d89dd6-84ff-4335-8a8a-0a42d58639cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit-login&quot;)</value>
      <webElementGuid>d182bee4-6efc-4936-a343-68a5b26bef8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submit-login']</value>
      <webElementGuid>8cccf6a0-8e80-4acd-88ba-e52c13bd150f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/footer/button</value>
      <webElementGuid>2237dc8b-b570-4dc8-a2b6-ba3d7197ec32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mot de passe oublié ?'])[1]/following::button[1]</value>
      <webElementGuid>71e94b8d-b9bc-4146-83eb-461cd46d6d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Montrer'])[1]/following::button[1]</value>
      <webElementGuid>b6ad8971-6431-4fb5-9502-9ec2991a3ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Créer un compte'])[1]/preceding::button[1]</value>
      <webElementGuid>d02b8d6b-b837-48d4-ab81-e8a8f1483241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button</value>
      <webElementGuid>321f40b2-22c2-41ea-8dd4-6abcb537e61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'submit-login' and @type = 'submit' and (text() = '
            Connexion
          ' or . = '
            Connexion
          ')]</value>
      <webElementGuid>0a0af7b9-8491-4635-bd76-e06e982b04ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
