<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Connexion</name>
   <tag></tag>
   <elementGuidId>2b2943df-769c-48fc-8167-4c158c10d4a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submit-login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submit-login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Connexion&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f760c3cc-46dc-44e5-bb26-fe70fa62913e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit-login</value>
      <webElementGuid>811f28fa-46ab-45c8-bd36-2777d3348dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>d04b9ed6-d7ca-4d10-8c90-fa8621403660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link-action</name>
      <type>Main</type>
      <value>sign-in</value>
      <webElementGuid>f5621a05-bd27-47e8-890d-61a6a04b35ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9f56beed-936c-4a34-aa7f-f3c91aa64cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Connexion
          </value>
      <webElementGuid>10cdfee8-c0f3-4d96-8745-0cf759deba70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit-login&quot;)</value>
      <webElementGuid>efa8aa96-d357-4a2a-9a00-9dfd2fcfce12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submit-login']</value>
      <webElementGuid>b175907f-c707-4e4f-a547-0bf61fdd3cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/footer/button</value>
      <webElementGuid>dc4271e5-8f42-4b95-8efb-376c14d06e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mot de passe oublié ?'])[1]/following::button[1]</value>
      <webElementGuid>170f5a71-332f-4167-a3f9-2c54feb570c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Montrer'])[1]/following::button[1]</value>
      <webElementGuid>a84d5c78-89b6-4649-b5e4-be5c78f41322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Créer un compte'])[1]/preceding::button[1]</value>
      <webElementGuid>b65a83a3-6a0d-409e-b1b1-99e103888b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button</value>
      <webElementGuid>c51b3962-6ce2-44fa-a414-113b35c4b42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'submit-login' and @type = 'submit' and (text() = '
            Connexion
          ' or . = '
            Connexion
          ')]</value>
      <webElementGuid>a4f4ffd5-4af7-4af3-8f05-880b6455cb52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
