<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_delete</name>
   <tag></tag>
   <elementGuidId>ef928171-2322-471a-a56a-e0214f0a00e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.material-icons.pull-xs-left</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_desktop_cart']/div/div/div/div/div/div/div[2]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;delete&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>cb687d31-44cb-4be3-8f3f-2f401375bb75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons pull-xs-left</value>
      <webElementGuid>faff2779-26a1-4730-9314-6b2c7907dae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>8a037ff4-4a39-46dd-a72a-1c3d2960ce5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_desktop_cart&quot;)/div[@class=&quot;blockcart cart-preview active&quot;]/div[@class=&quot;header blockcart-header dropdown js-dropdown open&quot;]/div[@class=&quot;cart_block block exclusive dropdown-menu&quot;]/div[@class=&quot;block_content&quot;]/div[@class=&quot;cart_block_list&quot;]/div[@class=&quot;cart-item&quot;]/div[@class=&quot;cart-info&quot;]/a[@class=&quot;remove-from-cart&quot;]/i[@class=&quot;material-icons pull-xs-left&quot;]</value>
      <webElementGuid>4407ceed-d89d-44c1-b814-f975682717ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_desktop_cart']/div/div/div/div/div/div/div[2]/a/i</value>
      <webElementGuid>41f0c596-db72-4c06-9f2d-d14d7c86b57a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blouson'])[2]/following::i[1]</value>
      <webElementGuid>aea5fb69-760e-452d-954c-44750e01a5d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[5]/following::i[1]</value>
      <webElementGuid>bedbf38b-67b6-44f0-9c6b-2c143e2b6644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Livraison'])[1]/preceding::i[1]</value>
      <webElementGuid>6d7752cd-0fc5-410a-9cc9-a69779379b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total (HT)'])[1]/preceding::i[1]</value>
      <webElementGuid>f835e37e-c184-404a-b151-06abfb4d277f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='delete']/parent::*</value>
      <webElementGuid>5a7c6ffb-690a-4786-aec3-24b350f17500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/i</value>
      <webElementGuid>f55af6ac-7ee8-41ba-b6ff-4349895fb37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'delete' or . = 'delete')]</value>
      <webElementGuid>2f742b59-1a80-448a-9424-75683ed38399</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
