<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Connexion</name>
   <tag></tag>
   <elementGuidId>c38d1701-9b11-4032-8338-50c6abfee4af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Identifiez-vous&quot;] > span.hidden-md-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_desktop_user_info']/ul/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Connexion&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6012d991-30ca-44da-a4bc-1e3b379fc9b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hidden-md-down</value>
      <webElementGuid>f40cd709-649e-497d-bcb2-3cfe6ad73e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Connexion</value>
      <webElementGuid>ea489691-1409-430a-8154-f6af3a7d167d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/nav[@class=&quot;header-nav&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;hidden-md-down&quot;]/div[@class=&quot;right-nav&quot;]/div[@id=&quot;_desktop_user_info&quot;]/ul[@class=&quot;user-info&quot;]/a[1]/span[@class=&quot;hidden-md-down&quot;]</value>
      <webElementGuid>0b2e980d-a504-4637-8a40-e4ceb0fcb6db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_desktop_user_info']/ul/a/span</value>
      <webElementGuid>35ea0401-3930-42e1-aa4e-3db915e69661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::span[1]</value>
      <webElementGuid>4c333d2f-c2a1-4e82-bd09-8aab929cb66c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::span[1]</value>
      <webElementGuid>4f259234-d23e-425d-b37e-cdd176618c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='social media'])[1]/preceding::span[1]</value>
      <webElementGuid>be4b26b0-5c42-489b-83ba-6c5351994c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/preceding::span[1]</value>
      <webElementGuid>4c800206-11fe-4144-b22f-3720fe52e0fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Connexion']/parent::*</value>
      <webElementGuid>a8304447-d39a-43b8-a6f6-970757ac1e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>e4696734-bc18-4677-a05a-c8fb2c95f6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Connexion' or . = 'Connexion')]</value>
      <webElementGuid>2baa8332-1796-44e2-8f0a-23b2600c647e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
