<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dconnexion</name>
   <tag></tag>
   <elementGuidId>5d4f2a79-2968-4e28-b360-1d9d55f74b6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.logout.hidden-md-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_desktop_user_info']/ul/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Déconnexion&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4474188e-12df-436e-b732-ec1ac56132d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logout hidden-md-down</value>
      <webElementGuid>7bd6aa15-1017-4a27-930c-40a3b51e0ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.exist.com.tn/?mylogout=</value>
      <webElementGuid>4371161d-7bbb-4896-8167-a973362f957f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>e86a52da-04ca-4713-b16e-35cb2e22e17c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        
        Déconnexion
      </value>
      <webElementGuid>82b513a0-e381-4fe8-bbaf-0b1b76217d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/nav[@class=&quot;header-nav&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;hidden-md-down&quot;]/div[@class=&quot;right-nav&quot;]/div[@id=&quot;_desktop_user_info&quot;]/ul[@class=&quot;user-info&quot;]/a[@class=&quot;logout hidden-md-down&quot;]</value>
      <webElementGuid>cb8d238c-2a64-488b-b29a-e803d46fe8d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_desktop_user_info']/ul/a</value>
      <webElementGuid>679b5e84-a56e-4d72-a223-8bdd98ff659a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::a[1]</value>
      <webElementGuid>4b72124e-f671-4e99-b3fc-426de1c5892a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon compte'])[2]/following::a[2]</value>
      <webElementGuid>9b8ab867-f9fb-44a4-b456-ff1f209e4100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::a[1]</value>
      <webElementGuid>78afe9d7-c7fe-4d66-8376-d36995cc70ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Déconnexion']/parent::*</value>
      <webElementGuid>3f2ae9d5-e7f0-42ee-9056-6ec0aa5693c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.exist.com.tn/?mylogout=')]</value>
      <webElementGuid>4050bdbd-a86e-4e08-bd54-9412ed117f54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/a</value>
      <webElementGuid>ab842662-0984-4241-92ea-a6889c6a86ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.exist.com.tn/?mylogout=' and (text() = '
        
        Déconnexion
      ' or . = '
        
        Déconnexion
      ')]</value>
      <webElementGuid>d9eaecce-988a-426c-afb4-eeb8afffb88b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
